steps:
  # 1. Build the Docker container image
  - id: 'build-image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-west1-docker.pkg.dev/$PROJECT_ID/rentcast-repo/pipeline:latest', '.']

  # 2. Push the image to Google Artifact Registry
  - id: 'push-image'
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/rentcast-repo/pipeline:latest']

  # 3. Deploy the image to a Cloud Run Job
  - id: 'deploy-job'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'real-estate-pipeline-job'
      - '--image'
      - 'us-west1-docker.pkg.dev/$PROJECT_ID/rentcast-repo/pipeline:latest'
      - '--region'
      - 'us-west1'
      - '--max-retries'
      - '3'
      - '--set-secrets'
      - 'RENTCAST_API_KEY=RENTCAST_API_KEY:latest'

# Inform Cloud Build which images to manage and verify
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/rentcast-repo/pipeline:latest'

options:
  # Bypass the legacy Service Account / Logging bucket error
  logging: CLOUD_LOGGING_ONLY
